title: Ramulator2 
email: mainpower4309@gmail.com
permalink: /docs_ramulator2

# Build settings
#theme: "just-the-docs" # for local
remote_theme: pmarsceill/just-the-docs # for github

# Callout definition
callouts:
  warning:
    color: yellow
  important:
    color: blue
  danger:
    color: red


